#! /bin/bash

#insert 1, shehab, 24 into tableName

if [[ -z $CURRENTDB ]]
    then
    echo Error: you must connect to database first
else
    source $HOME/bin/shql/helpers/helpers

    
    
    values="$(beforeWord "$*" "into")"
    tableName=$(afterWord "$*" "into")
    splitedValues=()
    split "$values" "," splitedValues

    #check meta file to get info about table (number of columns, type of each column)

    metaFile=$HOME/shql_db/$CURRENTDB/meta/$tableName
    tableFile=$HOME/shql_db/$CURRENTDB/$tableName

    if [ -f $tableFile -a -f $metaFile ]
        then
        columnsCount=`head -n 1 $metaFile | awk -F: '{print $2}'`
        if [ ${#splitedValues[@]} -eq $columnsCount ]
            then
            if duplicateKey "${splitedValues[0]}" $tableName ; then
                echo "Error: duplicate key (${splitedValues[0]})"
            else
                echo $(echo $values | awk '{gsub(/,/,":"); print}') >> $tableFile
            fi
        else
            echo "Erro: Your table has $columnsCount columns, you entered ${#splitedValues[@]} values"
        fi
    else
        echo table: $tableName does not exist
    fi
fi

