#! /bin/bash

#select cols from table_name where condition

source $HELPERS

if [[ -z $CURRENTDB ]]
    then
    echo Error: connect to database first

else
    columns=$(beforeWord "$*" "from")
    temp=$(afterWord "$*" "from")
    tableName=$(beforeWord "$temp" "where")

    #condition
    

    tableFile="$HOME/shql_db/$CURRENTDB/$tableName"
    metaFile="$HOME/shql_db/$CURRENTDB/meta/$tableName"

    if [ -f $tableFile -a -f $metaFile ]
    then

        if [ "$columns" == "all" ]
            then
            splitedColumns=($(sed "1d" $metaFile | awk -F: '{print $1}'))
        else
            splitedColumns=($(split "$columns" ","))
        fi

        colNumbers=()

        error=''
        for col in "${splitedColumns[@]}"
        do
            number=`colNumber $tableName $col`
            if [ -z $number ]
                then
                echo "Error: table ($tableName) does not have column ($col)"
                error="error"
                break
            fi
            colNumbers+=($number)
        done
        if [ -z $error ]
            then
            fields=''
            for num in "${colNumbers[@]}"
            do
                fields="$fields,$num"
            done 
            #remove first character
            fields="${fields#?}"
            echo "------------------------------"
            echo "${splitedColumns[@]}"
            echo "------------------------------"
            for line in $(cat $tableFile)
            do
                echo $( echo $line | cut -d ":" -f $fields --output-delimiter=" ")
            done
        fi
    else
        echo "Error: table ($tableName) does not exist"
    fi
fi

